services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./templates:/templates
    env_file:
      - .env
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_ORG: JHADigitalCore
      PR_REPOS: |
        general-ledger-service,
        general-ledger-translation-service,
        general-ledger-transfers-processor,
        general-ledger-manual-journal-processor,
        general-ledger-import-service,
        environments+label:general-ledger,
        k8s-apps+label:general-ledger
      ACTION_REPOS: |
        general-ledger-service,
        general-ledger-translation-service,
        general-ledger-transfers-processor,
        general-ledger-manual-journal-processor,
        general-ledger-import-service
      ACTION_FILTER: deploy
