services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./
          target: ./app
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
    ports:
      - 8888:8888
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_REPOS: ${GITHUB_REPOS}
