services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    env_file:
      - .env
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      PR_REPOS: |
        JHADigitalCore/general-ledger-service,
        JHADigitalCore/general-ledger-translation-service,
        JHADigitalCore/general-ledger-transfers-processor,
        JHADigitalCore/general-ledger-manual-journal-processor,
        JHADigitalCore/general-ledger-import-service,
        JHADigitalCore/environments?label=general-ledger,
        JHADigitalCore/k8s-apps?label=general-ledger
      ACTION_REPOS: |
        JHADigitalCore/general-ledger-service,
        JHADigitalCore/general-ledger-translation-service,
        JHADigitalCore/general-ledger-transfers-processor,
        JHADigitalCore/general-ledger-manual-journal-processor,
        JHADigitalCore/general-ledger-import-service
      ACTION_FILTER: deploy
