services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    develop:
      watch:
        - action: rebuild
          path: ./
          target: ./app
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
    ports:
      - 3000:3000