services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: ./app
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum