services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    env_file:
      - .env
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MONITOR_PR_REPOS: ${MONITOR_PR_REPOS}
      MONITOR_ACTION_REPOS: ${MONITOR_ACTION_REPOS}
